[workspace]
members = [ "hello_bevy","hello_world", "my_library", "pig"]
resolver = "3"

[workspace.dependencies]
bevy = "0.17" # maybe add features = ["wayland"] on linux
bevy_egui = "0.38.0"
rand = "0.9.2"
rand_xorshift = "0.4.0"
rand_pcg  = "0.9.0"
